### ISSUE TITLE
inconsistency with ai output

### ISSUE THREAD

**Issue by dejl** [z0rzi/ai-chat.nvim#3]
Hello
I'm trying out using the typescript program directly with terminal like so:

$ `bun copilot/index.ts chat test >> test`

```
$ cat test                                                            
# === USER ===\n
hello there, my name is d\n
# === AI ===\n
Hello d! How can I assist you today?\n
# === USER ===\n
say hello\n
# === AI ===
Sure! I can help you with that. If you want to print "Hello" in most programming languages, you can use the `print` statement or function. Could you please let me know which programming language you are using?
# === USER ===\n
could you tell me how to do the same in Python\n
Certainly! In Python, you can use the `print()` function to display "Hello" on the console. Here's an example:

python
print("Hello")


When you run this code, it will output "Hello" in the console.
```

It seems to be inconsistent with it's result, some times prepending the AI tag and some times not

is this an issue?

**Comment by z0rzi** [comment]
Hi there!

The typescript code was not meant to be used on its own, and the behavior you're observing is what should happen in the current version.
The `index.ts` file, in chat mode only returns the AI answer, without heading or anything, just the raw text answer.

The lua code is in charge of adding the `# === USER ===` and `# === AI ===` tags, over [here](https://github.com/z0rzi/ai-chat.nvim/blob/e6c32555c41905bf4b1585ba86d8a1572dc82c94/lua/ai-chat.lua#L212-L218)

But I do agree with you that the way it's done right now is not the best, where both the lua and the typescript do a bit of parsing... I should move it completely to one side or the other.

---

If you want the ts code to work as a standalone, you can just `console.log('# === AI ===')` before printing the answer in the `index.ts`.

**Comment by dejl** [comment]
thanks
one other query is does the access token need to be refreshed manually?
