### ISSUE TITLE
Co-pilot does not respond to any text.

### ISSUE THREAD

**Issue by carlesoctav** [z0rzi/ai-chat.nvim#5]
any idea how can i fix this?
![image](https://github.com/z0rzi/ai-chat.nvim/assets/106587439/fc632535-8f04-4f91-b5be-01a124e15610)

![image](https://github.com/z0rzi/ai-chat.nvim/assets/106587439/ad68e508-8d1f-4d1d-a503-1eda002b3f18)

after i update the plugin from lazy.

**Comment by z0rzi** [comment]
The Copilot URL changed, and the one I was using got deprecated (see [here](https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints))

I just pushed the fix 👍

**Comment by carlesoctav** [comment]
the bug is still happening
```
Failed to run `config` for ai-chat.nvim

...ctav/.local/share/nvim/lazy/ai-chat.nvim/lua/ai-chat.lua:52: attempt to index local 'handle' (a nil value)

# stacktrace:
  - /ai-chat.nvim/lua/ai-chat.lua:52 _in_ **copy_file**
  - /ai-chat.nvim/lua/ai-chat.lua:463 _in_ **verify_default_core_exist**
  - /ai-chat.nvim/lua/ai-chat.lua:525 _in_ **setup**
  - ~/.config/nvim/lua/plugins/copilot.lua:3 _in_ **config**
  - nvim/init.lua:16

```

**Comment by z0rzi** [comment]
Yes, my bad, I was writing to the core directory before creating it.... Fixed it. Let me know if it works now

**Comment by carlesoctav** [comment]
it's run well now. thanks.
